-- Wizard model
resource.AddFile("models/vinrax/player/gandalf.mdl")
resource.AddFile("models/vinrax/weapons/c_arms_gandalf.mdl")
resource.AddFile("materials/models/vinrax/player/gandalf/cape.vmt")
resource.AddFile("materials/models/vinrax/player/gandalf/clothes.vmt")
resource.AddFile("materials/models/vinrax/player/gandalf/face.vmt")
resource.AddFile("materials/models/vinrax/player/gandalf/hair.vmt")
resource.AddFile("materials/models/vinrax/player/gandalf/hands.vmt")
resource.AddFile("materials/models/vinrax/player/gandalf/weapon.vmt")

-- Warrior model
resource.AddFile("models/auditor/lotr/warriordude.mdl")
resource.AddFile("materials/models/auditor/lotr/warrior/body.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/face.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/face_n.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/hair.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/helmet.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/helmet_n.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/lightwarp_elchulus.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/lightwarp_flesh.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/neckguard.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/neckguard_n.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/phongwarp_metal2.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/shoulders.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/shoulders_n.vtf")
resource.AddFile("materials/models/auditor/lotr/warrior/tex_0067_0_dds.vmt")
resource.AddFile("materials/models/auditor/lotr/warrior/tex_0067_0_ddsn.vtf")

-- Rogue model
resource.AddFile("models/player/shay_cormac.mdl")
resource.AddFile("models/player/shay_cormac_hands.mdl")
resource.AddFile("materials/models/player/shaycormac/shay_body1.vmt")
resource.AddFile("materials/models/player/shaycormac/shay_body1_n.vtf")
resource.AddFile("materials/models/player/shaycormac/shay_body2.vmt")
resource.AddFile("materials/models/player/shaycormac/shay_body2_n.vtf")
resource.AddFile("materials/models/player/shaycormac/shay_eye.vmt")
resource.AddFile("materials/models/player/shaycormac/shay_face.vmt")
resource.AddFile("materials/models/player/shaycormac/shay_face_n.vtf")
resource.AddFile("materials/models/player/shaycormac/shay_hair.vmt")
resource.AddFile("materials/models/player/shaycormac/shay_hair_n.vtf")
resource.AddFile("materials/models/player/shaycormac/shay_mouth.vmt")

-- Medic model
resource.AddFile("models/payday2/units/medic_player.mdl")
resource.AddFile("models/payday2/units/medic_arms.mdl")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_df.vmt")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_head_df.vmt")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_head_nm.vtf")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_head_sp.vtf")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_nm.vtf")
resource.AddFile("materials/models/payday2/units/medic/ene_medic_sp.vtf")