GM.Name = "Battle Boss Battle"
GM.Author = "add___123 - itsmeaddof123#0773"

--[[ Credits:

    Models for melee weapons: https://steamcommunity.com/sharedfiles/filedetails/?id=369150821
    Some free sounds were from here: https://www.soundjay.com/index.html
    Wizard model: https://steamcommunity.com/sharedfiles/filedetails/?id=788109554
    Warrior model: https://steamcommunity.com/sharedfiles/filedetails/?id=1275272057
    Rogue model: https://steamcommunity.com/sharedfiles/filedetails/?id=442214334
    Medic model: https://steamcommunity.com/sharedfiles/filedetails/?id=892493593
    Songs are from HL1 and HL2 so they were already in gmod
    Crafting icons are open source clip art since I can't draw
    Gamemode icon and logo by https://steamcommunity.com/id/Shadow01100/ and with help on the logo by Dog

--]]

-- Crafting items setup info
craftingTable = {
    items = {
        {image = "menu/melee.png",
            {name = "Enchanted Knife",
                desc = "Preferred by the Wizard, this cardboard cut-out of a knife has been given magical sharpness.",
                image = "menu/enchantedknife.png",
                cost = {1, 0, 0, 0, 3, 0,},}, -- Essence, stone, fur, metal, wood, water
            {name = "Kukri Blade",
                desc = "Preferred by the Warrior, this Indian blade will do well to hack through any enemies.",
                image = "menu/kukriblade.png",
                cost = {0, 3, 0, 3, 2, 0,},},
            {name = "Hunting Knife",
                desc = "Preferred by the Rogue, this knife will allow you to do some quick slashing.",
                image = "menu/huntingknife.png",
                cost = {0, 0, 3, 0, 2, 2,},},
            {name = "Combat Knife",
                desc = "Preferred by the Infantry, this handy weapon will keep you safe in a pinch.",
                image = "menu/combatknife.png",
                cost = {0, 1, 0, 3, 0, 0,},},
            {name = "Kitchen Knife",
                desc = "Preferred by the Berserker. Not sure what this is doing on a battlefield, but a knife is a knife.",
                image = "menu/kitchenknife.png",
                cost = {1, 0, 0, 0, 3, 0,},},
            {name = "Bone Cleaver",
                desc = "Preferred by the medic, this vampiric blade will heal you every time you strike an enemy.",
                image = "menu/bonecleaver.png",
                cost = {1, 3, 0, 0, 0, 4,},},},
        {image = "menu/ranged.png",
            {name = "Magic Wand",
                desc = "Preferred by the Wizard, this wand will blast your enemies with waves of raw power!",
                image = "menu/magicwand.png",
                cost = {4, 0, 2, 0, 2, 0,},},
            {name = "Speed Sac",
                desc = "Preferred by the Warrior, this juicy ball will boost your speed when used so you can charge enemies!",
                image = "menu/speedsac.png",
                cost = {0, 2, 0, 2, 0, 0,},},
            {name = "Crossbow",
                desc = "Preferred by the Rogue, this wooden mechanism will provide you with a reliable weapon on the go.",
                image = "menu/crossbow.png",
                cost = {0, 0, 3, 0, 2, 0,},},
            {name = "Light SMG",
                desc = "Preferred by the Infantry, this automatic weapon has unlimited reloads and a high firerate.",
                image = "menu/lightsmg.png",
                cost = {0, 2, 2, 4, 0, 0,},},
            {name = "Heavy Blaster",
                desc = "Preferred by the Beserker, this powerful rifle has unlimited reolads and a high damage output.",
                image = "menu/heavyblaster.png",
                cost = {3, 1, 0, 0, 4, 0,},},
            {name = "Medkit",
                desc = "Preferred by the Medic, this life-saving kit will heal you on each use.",
                image = "menu/medkit.png",
                cost = {0, 0, 1, 0, 0, 3,},},},
        {image = "menu/drink.png",
            {name = "Swirling Elixir",
                desc = "This will transform you into a Wizard, boosting the strength of the Enchanted Knife and Magic Wand.",
                image = "menu/elixir.png",
                cost = {4, 0, 2, 0, 0, 0,},
                mdl = "models/vinrax/player/gandalf.mdl",
                weak = "Rogue"},
            {name = "Bubbling Ale",
                desc = "This will transform you into a Warrior, boosting the strength of the Kukri Blade and Speed Sac.",
                image = "menu/ale.png",
                cost = {0, 4, 0, 0, 2, 0,},
                mdl = "models/auditor/lotr/warriordude.mdl",
                weak = "Wizard"},
            {name = "Invigorating Tonic",
                desc = "This will transform you into a Rogue, boosting the strength of the Hunting Knife and Crossbow.",
                image = "menu/tonic.png",
                cost = {0, 0, 4, 0, 0, 2,},
                mdl = "models/player/shay_cormac.mdl",
                weak = "Warrior"},
            {name = "Black Espresso",
                desc = "This will transform you into an Infantry, boosting the strength of the Combat Knife and Light SMG.",
                image = "menu/espresso.png",
                cost = {0, 2, 0, 4, 0, 0,},
                mdl = "models/player/police.mdl",
                weak = "Berserker"},
            {name = "Whiskey Glass",
                desc = "This will transform you into a Berserker, boosting the strength of the Kitchen Knife and Heavy Blaster.",
                image = "menu/whiskey.png",
                cost = {2, 0, 0, 0, 4, 0,},
                mdl = "models/player/combine_soldier_prisonguard.mdl",
                weak = "Infantry"},
            {name = "Mineral Water",
                desc = "This will transform you into a Medic, boosting the strength of Bone Cleave and Medkit.",
                image = "menu/mineralwater.png",
                cost = {0, 0, 2, 0, 0, 4,},
                mdl = "models/payday2/units/medic_player.mdl",
                weak = "Medic"},},
        {image = "menu/mark.png",
            {name = "Mark of the Wizard",
                desc = "Wearing this will raise your ranged strength but lower your maximum shield.",
                image = "menu/markwizard.png",
                cost = {3, 1, 0, 0, 0, 0,},},
            {name = "Mark of the Warrior",
                desc = "Wearing this will raise your melee strength but lower your ranged strength.",
                image = "menu/markwarrior.png",
                cost = {0, 3, 0, 0, 1, 0,},},
            {name = "Mark of the Rogue",
                desc = "Wearing this will raise your jumping power and speed but lower your maximum health.",
                image = "menu/markrogue.png",
                cost = {0, 0, 3, 0, 0, 1,},},
            {name = "Mark of the Infantry",
                desc = "Wearing this will raise your ranged strength but lower your melee strength.",
                image = "menu/markgunman.png",
                cost = {0, 1, 0, 3, 0, 0,},},
            {name = "Mark of the Berserker",
                desc = "Wearing this will raise your attack strength but lower your speed.",
                image = "menu/markberserker.png",
                cost = {1, 0, 0, 0, 3, 0,},},
            {name = "Mark of the Medic",
                desc = "Wearing this will raise your shield regeneration speed but lower your attack strength.",
                image = "menu/markmedic.png",
                cost = {0, 0, 1, 0, 0, 2,},},},
        {image = "menu/equip.png",
            {name = "Wizard's Tome",
                desc = "Crafting this ancient artifact will boost your ranged strength.",
                image = "menu/tome.png",
                cost = {3, 0, 1, 0, 1, 1,},},
            {name = "Warrior's Shield",
                desc = "Crafting this trusty protection will boost your defense.",
                image = "menu/shield.png",
                cost = {1, 3, 0, 1, 1, 0,},},
            {name = "Rogue's Boots",
                desc = "Crafting these featherweight shoes will boost your speed.",
                image = "menu/boots.png",
                cost = {0, 0, 3, 1, 1, 1,},},
            {name = "Infantry's Pack",
                desc = "Crafting this military grade backpack will boost your maximum shield.",
                image = "menu/pack.png",
                cost = {0, 1, 1, 3, 0, 1,},},
            {name = "Berserker's Bomb",
                desc = "Crafting this dangerous explosive will boost your melee strength.",
                image = "menu/bomb.png",
                cost = {1, 1, 0, 1, 3, 0,},},
            {name = "Medic's Syringe",
                desc = "Crafting this medical tool will boost your maximum health.",
                image = "menu/syringe.png",
                cost = {1, 1, 1, 0, 0, 3,},},},
        {image = "menu/consumable.png",
            {name = "Health Kit",
                desc = "This will give you 50 health as a last resort.",
                image = "menu/healthkit.png",
                cost = {3, 1, 0, 0, 0, 0,},},
            {name = "Circular Shield",
                desc = "This will increase your defense for 30 seconds.",
                image = "menu/circularshield.png",
                cost = {0, 3, 0, 0, 0, 1,},},
            {name = "Shield Patch",
                desc = "This will give you 50 shield instantly.",
                image = "menu/shieldpatch.png",
                cost = {1, 0, 3, 0, 0, 0,},},
            {name = "Shield Battery",
                desc = "This will boost your shield regeneration speed for 30 seconds.",
                image = "menu/shieldbattery.png",
                cost = {0, 0, 0, 3, 1, 0,},},
            {name = "Protein Powder",
                desc = "This will boost your attack strength for 30 seconds.",
                image = "menu/proteinpowder.png",
                cost = {0, 0, 1, 0, 3, 0,},},
            {name = "Energy Booster",
                desc = "This will increase your speed and jump power for 30 seconds.",
                image = "menu/energybar.png",
                cost = {0, 0, 0, 1, 0, 3,},},},},
    materials = {
        "menu/essence.png",
        "menu/stone.png",
        "menu/fur.png",
        "menu/ingot.png",
        "menu/wood.png",
        "menu/water.png",},
    ranks = {
        ["Wizard"] = "Battle: Wizard! You do increased damage to warriors, you have increased mana regen, and you get a point boost! Now go fight!",
        ["Warrior"] = "Battle: Warrior! You do increased damage to rogues, you have increased strength, and you get a point boost! Now go fight!",
        ["Rogue"] = "Battle: Rogue! You do increased damage to wizards, you have increased speed, and you get a point boost! Now go fight!",
        ["Infantry"] = "Battle: Infantry! You do increased damage to berserkers, you have an improved gun, and you get a point boost! Now go fight!",
        ["Berserker"] = "Battle: Berserker! You do increased damage to gunmen, you take no damage from your club, and you get a point boost! Now go fight!",
        ["Medic"] = "Battle: Medic! You do increased damage to other medics, you have automatic health regeneration, and you get a point boost! Now go fight!",
        ["Wild Card"] = "Battle: Wild Card! You have increased defense, do extra damage to the battle boss, and you get a big point boost! Now go fight!",
        ["Overtrained"] = "Battle: Overtrained! All your stats are increased even more and you get a big point boost! Now go fight!",
        ["Collector"] = "Battle: Collector! You spent the whole round collecting materials? Congratulations, take this plastic knife.",
        ["Master Chemist"] = "Battle: Master Chemist! Your consumables are three times as effective and you get a big point boost! Now go fight!",
        ["Classless"] = "Battle: Classless. Next time, try crafting a full set of gear. If you experiment, you might be able to discover some secret classes! Now go fight!",
        ["Battle Boss"] = "Battle: Your weapons and abilities have been upgraded! Go now, wreak havoc, and show your enemies what makes you Battle Boss!"
    }
}

function GM:Initialize()

    self.BaseClass.Initialize(self)

end